### ISSUE TITLE
Shell script in launch options

### ISSUE THREAD

**Issue by ghost** [rage311/linux_gaming_tweaks#1]
Could you elaborate on how you make CS:GO launch a shell script? For example, putting
```
/home/l2y/bin/linux_gaming_tweaks.sh start; -freq 60 -console -novid -tickrate 128;  /home/l2y/bin/linux_gaming_tweaks.sh stop
```
doesn't execute the "start" part (I've modified the script so I can tell when it is executed, and when it isn't), but always executes the "stop" part when `exit`ing the game. The script is `chmod +x`ed.

**Comment by rage311** [comment]
Make sure you're including the literal string `%command%` before your CS:GO launch options, like this:

`/home/l2y/bin/linux_gaming_tweaks.sh start; `**`%command%`**` -freq 60 -console -novid -tickrate 128;  /home/l2y/bin/linux_gaming_tweaks.sh stop`

This is a direct copy and paste from my CS:GO launch options:
`$HOME/dev/linux_gaming_tweaks/linux_gaming_tweaks.sh start; %command% -refresh 100 -high -threads 8 -nod3d9ex -nod3d9ex1 -novid -nojoy +cl_forcepreload 1 +mat_queue_mode -2; $HOME/dev/linux_gaming_tweaks/linux_gaming_tweaks.sh stop`

I just tested it on my machine, and even though the game still launches without having `%command%` in there, it doesn't seem to run the `start` portion.

**Comment by ghost** [comment]
Thank you.
